<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>.Promise的链式调用</title>
	</head>
	<body>
		<script>
			/*
				无论是then还是catch都可以返回一个Promise对象。
				所以，代码其实是可以进行链式调用的:
				这里直接通过Promise包装了一下新的数据，将Promise对象返回了
					Promise.resovle():将数据包装成Promise对象，并且在内部回调resolve()函数
					Promise.reject():将数据包装成Promise对象，并且在内部回调reject()函数
			*/
			new Promise((resolve,reject)=>{
				setTimeout(function(){
					resolve("hello world")
				},1000)
			}).then(data=>{
				console.log(data);//=>Hello World
				return new Promise((resolve,reject)=>{
					resolve(data + "111")
				})
			}).then(data=>{
				console.log(data);// => Hello World111
				return new Promise((resolve,reject)=>{
					resolve(data + "222")
				})
			}).then(data=>{
				console.log(data)// => Hello World111222
				return new Promise((resolve,reject)=>{
					reject(data + "error")
				})
			}).then(data=>{
				console.log(data)// 这里没有输出,这部分代码不会执行
				return new Promise((resolve,reject)=>{
					resolve(data + "333")
				})
			}).catch(data =>{
				console.log(data)// =→>Hello world111222error
				return new Promise((resolve,reject)=>{
					resolve(data + "444")
				})
			}).then(data=>{
				console.log(data)//=> Hello World111222error444
			})
		</script>
	</body>
</html>
